import { Injectable } from '@nestjs/common';
import { TradeDocument, DocumentStatus } from './entities/trade-document.entity';
import { DocumentCategory } from '../../common/enums';

@Injectable()
export class DocumentGeneratorService {
  async generate(doc: TradeDocument): Promise<string> {
    const templates: Record<string, (doc: TradeDocument) => Promise<string>> = {
      [DocumentCategory.COMMERCIAL_INVOICE]: this.generateCommercialInvoice.bind(this),
      [DocumentCategory.PACKING_LIST]: this.generatePackingList.bind(this),
      [DocumentCategory.BILL_OF_LADING]: this.generateBillOfLading.bind(this),
      [DocumentCategory.CERTIFICATE_OF_ORIGIN]: this.generateCertificateOfOrigin.bind(this),
      [DocumentCategory.CUSTOMS_INVOICE]: this.generateCustomsDeclaration.bind(this),
      [DocumentCategory.INSURANCE_CERTIFICATE]: this.generateInsuranceCertificate.bind(this),
      [DocumentCategory.LETTER_OF_CREDIT]: this.generateLetterOfCredit.bind(this),
    };

    const generator = templates[doc.type];
    if (generator) {
      return generator(doc);
    }
    return this.generateGeneric(doc);
  }

  private async generateCommercialInvoice(doc: TradeDocument): Promise<string> {
    const content = typeof doc.content === 'string' ? JSON.parse(doc.content || '{}') : (doc.content || {});
    const items = content.items || [];

    const itemsHtml = items.map((item: any) => `
      <tr>
        <td>${this.escapeHtml(item.description || '')}</td>
        <td>${item.quantity || 0}</td>
        <td>${item.unitPrice || 0}</td>
        <td>${item.total || 0}</td>
      </tr>
    `).join('');

    const html = `
      <!DOCTYPE html>
      <html>
      <head>
        <meta charset="UTF-8">
        <style>
          body { font-family: Arial, sans-serif; margin: 40px; color: #333; }
          .header { text-align: center; margin-bottom: 40px; border-bottom: 2px solid #333; padding-bottom: 20px; }
          h1 { margin: 0; font-size: 28px; }
          .invoice-number { font-size: 20px; color: #666; margin-top: 10px; }
          .details { display: flex; justify-content: space-between; margin: 30px 0; }
          .details-box { width: 45%; }
          .details-box h3 { margin-bottom: 10px; color: #333; }
          table { width: 100%; border-collapse: collapse; margin: 20px 0; }
          th, td { border: 1px solid #ddd; padding: 12px 8px; text-align: left; }
          th { background-color: #f5f5f5; font-weight: bold; }
          .total-section { margin-top: 30px; text-align: right; }
          .total-section p { margin: 5px 0; font-size: 16px; }
          .grand-total { font-size: 20px; font-weight: bold; margin-top: 15px !important; }
          .footer { margin-top: 50px; text-align: center; font-size: 12px; color: #666; }
        </style>
      </head>
      <body>
        <div class="header">
          <h1>COMMERCIAL INVOICE</h1>
          <div class="invoice-number">${this.escapeHtml(doc.number || 'INV-' + Date.now())}</div>
        </div>

        <div class="details">
          <div class="details-box">
            <h3>Exporter</h3>
            <p>${this.escapeHtml(typeof doc.generatedBy === 'string' ? doc.generatedBy : JSON.stringify(doc.generatedBy))}</p>
          </div>
          <div class="details-box">
            <h3>Importer</h3>
            <p>${this.escapeHtml(typeof doc.generatedFor === 'string' ? doc.generatedFor : JSON.stringify(doc.generatedFor))}</p>
          </div>
        </div>

        <p><strong>Date:</strong> ${new Date().toLocaleDateString()}</p>
        <p><strong>Document ID:</strong> ${doc.id}</p>

        <table>
          <thead>
            <tr>
              <th>Description</th>
              <th>Quantity</th>
              <th>Unit Price</th>
              <th>Total</th>
            </tr>
          </thead>
          <tbody>
            ${itemsHtml || '<tr><td colspan="4">No items</td></tr>'}
          </tbody>
        </table>

        <div class="total-section">
          <p>Subtotal: ${this.formatCurrency(content.subtotal || 0, content.currency)}</p>
          <p>Tax: ${this.formatCurrency(content.tax || 0, content.currency)}</p>
          <p class="grand-total">Total: ${this.formatCurrency(content.total || 0, content.currency || 'USD')}</p>
        </div>

        <div class="footer">
          <p>Generated by Trade OS - Document ID: ${doc.id}</p>
        </div>
      </body>
      </html>
    `;

    // In production, convert HTML to PDF using puppeteer, pdf-lib, or similar
    // For now, return a mock URL
    return `https://storage.example.com/documents/${doc.id}.pdf`;
  }

  private async generatePackingList(doc: TradeDocument): Promise<string> {
    const html = `
      <!DOCTYPE html>
      <html>
      <head>
        <meta charset="UTF-8">
        <style>
          body { font-family: Arial, sans-serif; margin: 40px; }
          .header { text-align: center; margin-bottom: 30px; }
          table { width: 100%; border-collapse: collapse; }
          th, td { border: 1px solid #ddd; padding: 10px; }
          th { background-color: #f5f5f5; }
        </style>
      </head>
      <body>
        <div class="header">
          <h1>PACKING LIST</h1>
          <p>${this.escapeHtml(doc.number || 'PL-' + Date.now())}</p>
        </div>
        <p><strong>Shipper:</strong> ${this.escapeHtml(typeof doc.generatedBy === 'string' ? doc.generatedBy : JSON.stringify(doc.generatedBy))}</p>
        <p><strong>Consignee:</strong> ${this.escapeHtml(typeof doc.generatedFor === 'string' ? doc.generatedFor : JSON.stringify(doc.generatedFor))}</p>
        <p><strong>Document ID:</strong> ${doc.id}</p>
        <div class="footer">
          <p>Generated by Trade OS</p>
        </div>
      </body>
      </html>
    `;
    return `https://storage.example.com/documents/${doc.id}-pl.pdf`;
  }

  private async generateBillOfLading(doc: TradeDocument): Promise<string> {
    const html = `
      <!DOCTYPE html>
      <html>
      <head>
        <meta charset="UTF-8">
        <style>
          body { font-family: Arial, sans-serif; margin: 40px; }
          .header { text-align: center; border: 2px solid #000; padding: 20px; margin-bottom: 30px; }
          .section { margin: 20px 0; }
        </style>
      </head>
      <body>
        <div class="header">
          <h1>BILL OF LADING</h1>
          <p>${this.escapeHtml(doc.number || 'BOL-' + Date.now())}</p>
        </div>
        <div class="section">
          <p><strong>Shipper:</strong> ${this.escapeHtml(typeof doc.generatedBy === 'string' ? doc.generatedBy : JSON.stringify(doc.generatedBy))}</p>
          <p><strong>Consignee:</strong> ${this.escapeHtml(typeof doc.generatedFor === 'string' ? doc.generatedFor : JSON.stringify(doc.generatedFor))}</p>
        </div>
        <div class="section">
          <p><strong>Document ID:</strong> ${doc.id}</p>
        </div>
      </body>
      </html>
    `;
    return `https://storage.example.com/documents/${doc.id}-bol.pdf`;
  }

  private async generateCertificateOfOrigin(doc: TradeDocument): Promise<string> {
    return `https://storage.example.com/documents/${doc.id}-coo.pdf`;
  }

  private async generateBillOfExchange(doc: TradeDocument): Promise<string> {
    return `https://storage.example.com/documents/${doc.id}-boe.pdf`;
  }

  private async generateCustomsDeclaration(doc: TradeDocument): Promise<string> {
    return `https://storage.example.com/documents/${doc.id}-customs.pdf`;
  }

  private async generateInsuranceCertificate(doc: TradeDocument): Promise<string> {
    return `https://storage.example.com/documents/${doc.id}-insurance.pdf`;
  }

  private async generateLetterOfCredit(doc: TradeDocument): Promise<string> {
    return `https://storage.example.com/documents/${doc.id}-lc.pdf`;
  }

  private async generateGeneric(doc: TradeDocument): Promise<string> {
    return `https://storage.example.com/documents/${doc.id}.pdf`;
  }

  private escapeHtml(text: string): string {
    const map: Record<string, string> = {
      '&': '&amp;',
      '<': '&lt;',
      '>': '&gt;',
      '"': '&quot;',
      "'": '&#039;',
    };
    return text.replace(/[&<>"']/g, (m) => map[m]);
  }

  private formatCurrency(amount: number, currency: string = 'USD'): string {
    return `${currency} ${amount.toFixed(2)}`;
  }
}
