// Shared enums to avoid circular dependencies

export enum VerificationStatus {
  PENDING = 'PENDING',
  UNDER_REVIEW = 'UNDER_REVIEW',
  VERIFIED = 'VERIFIED',
  REJECTED = 'REJECTED',
}

export enum DocumentType {
  GST_CERTIFICATE = 'GST_CERTIFICATE',
  IEC = 'IEC',
  PAN_CARD = 'PAN_CARD',
  ADDRESS_PROOF = 'ADDRESS_PROOF',
  BANK_STATEMENT = 'BANK_STATEMENT',
  MOA_AOA = 'MOA_AOA',
  PARTNERSHIP_DEED = 'PARTNERSHIP_DEED',
  IMPORT_LICENSE = 'IMPORT_LICENSE',
  EXPORT_LICENSE = 'EXPORT_LICENSE',
  ISO_CERTIFICATE = 'ISO_CERTIFICATE',
  OTHER = 'OTHER',
}

export enum DocumentCategory {
  COMMERCIAL_INVOICE = 'COMMERCIAL_INVOICE',
  PACKING_LIST = 'PACKING_LIST',
  BILL_OF_LADING = 'BILL_OF_LADING',
  AIR_WAYBILL = 'AIR_WAYBILL',
  SEA_WAYBILL = 'SEA_WAYBILL',
  CERTIFICATE_OF_ORIGIN = 'CERTIFICATE_OF_ORIGIN',
  CERTIFICATE_OF_ANALYSIS = 'CERTIFICATE_OF_ANALYSIS',
  SHIPPING_BILL = 'SHIPPING_BILL',
  EXPORT_DECLARATION = 'EXPORT_DECLARATION',
  IMPORT_DECLARATION = 'IMPORT_DECLARATION',
  INSURANCE_CERTIFICATE = 'INSURANCE_CERTIFICATE',
  LETTER_OF_CREDIT = 'LETTER_OF_CREDIT',
  BILL_OF_ENTRY = 'BILL_OF_ENTRY',
  DELIVERY_ORDER = 'DELIVERY_ORDER',
  GOODS_DECLARATION = 'GOODS_DECLARATION',
  PHYTOSANITARY = 'PHYTOSANITARY',
  FUMIGATION_CERTIFICATE = 'FUMIGATION_CERTIFICATE',
  CONSULAR_INVOICE = 'CONSULAR_INVOICE',
  CUSTOMS_INVOICE = 'CUSTOMS_INVOICE',
  PACKING_DECLARATION = 'PACKING_DECLARATION',
  SHIPPER_LETTER_OF_INSTRUCTIONS = 'SHIPPER_LETTER_OF_INSTRUCTIONS',
  DANGEROUS_GOODS_DECLARATION = 'DANGEROUS_GOODS_DECLARATION',
}

export enum TransportMode {
  AIR = 'AIR',
  SEA = 'SEA',
  ROAD = 'ROAD',
  RAIL = 'RAIL',
  MULTIMODAL = 'MULTIMODAL',
}

export enum QuoteStatus {
  PENDING = 'PENDING',
  ACCEPTED = 'ACCEPTED',
  REJECTED = 'REJECTED',
  EXPIRED = 'EXPIRED',
}

export enum ShipmentStatus {
  DRAFT = 'DRAFT',
  BOOKED = 'BOOKED',
  PICKED_UP = 'PICKED_UP',
  IN_TRANSIT = 'IN_TRANSIT',
  OUT_FOR_DELIVERY = 'OUT_FOR_DELIVERY',
  DELIVERED = 'DELIVERED',
  CANCELLED = 'CANCELLED',
}

export enum SubscriptionStatus {
  ACTIVE = 'ACTIVE',
  PAST_DUE = 'PAST_DUE',
  CANCELLED = 'CANCELLED',
  TRIALING = 'TRIALING',
}

export enum PlanType {
  FREE = 'FREE',
  STARTER = 'STARTER',
  PROFESSIONAL = 'PROFESSIONAL',
  ENTERPRISE = 'ENTERPRISE',
}

export enum BillingInterval {
  MONTHLY = 'MONTHLY',
  QUARTERLY = 'QUARTERLY',
  YEARLY = 'YEARLY',
}

export enum InvoiceStatus {
  DRAFT = 'DRAFT',
  SENT = 'SENT',
  PAID = 'PAID',
  OVERDUE = 'OVERDUE',
  CANCELLED = 'CANCELLED',
}

export enum OrderStatus {
  PENDING = 'PENDING',
  CONFIRMED = 'CONFIRMED',
  PROCESSING = 'PROCESSING',
  SHIPPED = 'SHIPPED',
  DELIVERED = 'DELIVERED',
  CANCELLED = 'CANCELLED',
  REFUNDED = 'REFUNDED',
}

export enum PaymentStatus {
  PENDING = 'PENDING',
  PROCESSING = 'PROCESSING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  REFUNDED = 'REFUNDED',
}

export enum AdStatus {
  DRAFT = 'DRAFT',
  PENDING = 'PENDING',
  ACTIVE = 'ACTIVE',
  PAUSED = 'PAUSED',
  COMPLETED = 'COMPLETED',
  REJECTED = 'REJECTED',
}

export enum PostType {
  TEXT = 'TEXT',
  IMAGE = 'IMAGE',
  VIDEO = 'VIDEO',
  DOCUMENT = 'DOCUMENT',
  LINK = 'LINK',
}

export enum MessageStatus {
  SENT = 'SENT',
  DELIVERED = 'DELIVERED',
  READ = 'READ',
}
