export const mockUser = {
  id: 'user-1',
  email: 'alex.morgan@leverage.com',
  firstName: 'Alex',
  lastName: 'Morgan',
  role: 'admin',
  company: 'Global Trade Corp',
  phone: '+1 555-123-4567',
};

export const mockProducts = [
  {
    id: 'prod-1',
    name: 'Industrial Steel Coils',
    description: 'High-grade steel coils for manufacturing',
    price: 850,
    currency: 'USD',
    minOrder: 50,
    unit: 'tons',
    supplier: 'China Steel Works',
    country: 'CN',
    category: 'Raw Materials',
    hsCode: '7208.51',
    image: '/images/products/steel-coil.jpg',
    verified: true,
  },
  {
    id: 'prod-2',
    name: 'Basmati Rice Premium',
    description: 'Long grain basmati rice, 2-year aged',
    price: 1200,
    currency: 'USD',
    minOrder: 100,
    unit: 'tons',
    supplier: 'Punjab Exports',
    country: 'IN',
    category: 'Food & Agriculture',
    hsCode: '1006.30',
    image: '/images/products/rice.jpg',
    verified: true,
  },
  {
    id: 'prod-3',
    name: 'Cotton Yarn 40s',
    description: 'Pure cotton yarn for weaving',
    price: 3.5,
    currency: 'USD',
    minOrder: 10000,
    unit: 'kg',
    supplier: 'Textile Hub Vietnam',
    country: 'VN',
    category: 'Textiles',
    hsCode: '5205.11',
    image: '/images/products/yarn.jpg',
    verified: true,
  },
];

export const mockOrders = [
  {
    id: 'ord-1',
    product: 'Industrial Steel Coils',
    quantity: 200,
    total: 170000,
    status: 'in_transit',
    supplier: 'China Steel Works',
    eta: '2024-02-15',
    tracking: 'MSKU1234567',
  },
  {
    id: 'ord-2',
    product: 'Basmati Rice Premium',
    quantity: 50,
    total: 60000,
    status: 'processing',
    supplier: 'Punjab Exports',
    eta: '2024-02-20',
    tracking: null,
  },
];

export const mockRFQs = [
  {
    id: 'rfq-1',
    title: 'Steel Coils - Q1 2024',
    product: 'Industrial Steel Coils',
    quantity: 500,
    destination: 'Los Angeles, USA',
    deadline: '2024-01-30',
    status: 'open',
    responses: 3,
  },
  {
    id: 'rfq-2',
    title: 'Cotton Yarn Required',
    product: 'Cotton Yarn 40s',
    quantity: 50000,
    destination: 'Mumbai, India',
    deadline: '2024-02-10',
    status: 'quoting',
    responses: 7,
  },
];

export const mockMessages = [
  {
    id: 'msg-1',
    from: 'John Smith',
    company: 'Global Imports LLC',
    subject: 'Quote for Steel Coils',
    preview: 'We are interested in your steel coils...',
    time: '10 min ago',
    unread: true,
  },
  {
    id: 'msg-2',
    from: 'Priya Sharma',
    company: 'ExportCo India',
    subject: 'RE: Basmati Rice Inquiry',
    preview: 'Thank you for your interest. We can offer...',
    time: '1 hour ago',
    unread: true,
  },
  {
    id: 'msg-3',
    from: 'Mike Johnson',
    company: 'Pacific Trading',
    subject: 'Shipping Documentation',
    preview: 'Please find attached the Bill of Lading...',
    time: '3 hours ago',
    unread: false,
  },
];
